foot_tweet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('foot_tweet_app.urls')),
    path('admin/', admin.site.urls),
]

foot_tweet_app/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'foot_tweet_app'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'help/', views.help, name='help'),
    url(r'^show_team/$',views.show_team,name='show_team'),
    url(r'^show_player/$',views.show_player,name='show_player'),
]

foot_tweet_app/models.py
from django.db import models

# Create your models here.

class Twitter_Handles(models.Model):
    player_name = models.CharField(max_length=150)
    twitter_handle = models.CharField(max_length=100)
    team_name = models.CharField(max_length=150)
    player_position = models.CharField(max_length=10,default='')

class Tweets(models.Model):
    handle_id = models.BigIntegerField(default=0)
    player_name = models.CharField(max_length=150)
    screen_name = models.CharField(max_length=150,default='NA')
    created_at = models.CharField(max_length=100)
    tweet = models.CharField(max_length=1000)
    language = models.CharField(max_length=5)
    covid_time = models.IntegerField(default=9)

class Sentiment(models.Model):
    player_name = models.CharField(max_length=150)
    screen_name = models.CharField(max_length=150)
    created_at = models.CharField(max_length=100)
    cleaned_tweet = models.CharField(max_length=1000)
    covid_time = models.IntegerField(default=9)
    sentiment = models.CharField(max_length=15)

foot_tweet_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Twitter_Handles, Tweets, Sentiment
from django.db.models import Count
import json


def index(request):
    return render(request,'index.html')

def help(request):
    return render(request,'help.html')
    

def show_team(request):
    team_name = request.GET.get('team_name')
    team_data = Twitter_Handles.objects.filter(team_name=team_name)
    team_tweets = list(Tweets.objects.filter(player_name=team_name).order_by('-created_at').values_list('tweet',flat=True))[:5]
    return render(request,'teams.html',{'team':team_data,'team_tweets':team_tweets,'team_name':team_name})

def show_player(request):
    player_name = request.GET.get('player_name')
    player_data_no_covid = Sentiment.objects.filter(player_name=player_name,covid_time=0).values('sentiment').order_by('sentiment').annotate(count=Count('sentiment'))
    player_data_covid = Sentiment.objects.filter(player_name=player_name,covid_time=1).values('sentiment').order_by('sentiment').annotate(count=Count('sentiment'))

    no_covid_dict = dict([list(k.values()) for k in player_data_no_covid])
    covid_dict = dict([list(k.values()) for k in player_data_covid])

    categories = ['positive','neutral','negative']
    no_covid_counts = [no_covid_dict.get('positive',0),no_covid_dict.get('neutral',0),no_covid_dict.get('negative',0)]
    covid_counts = [covid_dict.get('positive',0),covid_dict.get('neutral',0),covid_dict.get('negative',0)]

    insight = ''

    if all(v == 0 for v in no_covid_counts) and all(v == 0 for v in covid_counts):
        insight = 'No Tweets to compare for {}'.format(player_name)
    elif ~all(v == 0 for v in no_covid_counts) and all(v == 0 for v in covid_counts):
        MaxKey = max(no_covid_dict, key=no_covid_dict.get)
        insight = '{} had more {} tweets before pandemic'.format(player_name,MaxKey)
    elif all(v == 0 for v in no_covid_counts) and ~all(v == 0 for v in covid_counts):
        MaxKey = max(covid_dict, key=covid_dict.get)
        insight = '{} had more {} tweets after pandemic'.format(player_name,MaxKey)
    else:
        MaxKey1 = max(no_covid_dict, key=no_covid_dict.get)
        MaxKey2 = max(covid_dict, key=covid_dict.get)
        if MaxKey1==MaxKey2:
            if no_covid_dict.get(MaxKey1,0)>=covid_dict.get(MaxKey2,0):
                insight = '{} was more {} when using twitter before pandemic'.format(player_name,MaxKey1)
            else:
                insight = '{} was more {} when using twitter after pandemic'.format(player_name,MaxKey1)
        else:
            insight = '{} was more {} when using twitter before pandemic and more {} after pandemic'.format(player_name,MaxKey1,MaxKey2)

    before_covid_series = {
        'name': 'Before COVID',
        'data': no_covid_counts,
        'color': 'blue'
    }

    after_covid_series = {
        'name': 'After COVID',
        'data': covid_counts,
        'color': 'orange'
    }

    title = 'Sentiment Distribution of Tweets for {}'.format(player_name)

    chart = {
        'chart': {'type': 'column'},
        'title': {'text': title},
        'xAxis': {'categories': categories},
        'series': [before_covid_series, after_covid_series]
        }

    dump = json.dumps(chart)

    return render(request, 'player.html', {'chart': dump,'player_name':player_name,'insight':insight})

foot_tweet_app/templates/help.html
<!DOCTYPE html>
{% extends "index.html" %}
{% load static %}

{% block body_block%}
{% block content %}
<body>
    <h1 style="padding-left:30% ;">Your help text</h1>
</body>
{% endblock %}
{% endblock %}
</html>

foot_tweet_app/templates/index.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Foot Tweet </title>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}"/>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script type="text/javascript" src="js/script.js"></script>

    <script>
        $(document).ready(function() {
            $("body").on('click', '.top', function() {
                $("nav.menu").toggleClass("menu_show");
            });
        });
        </script>

</head>
<body>
    <header>
		<h1 id="headr">Affect of the pandemic on premier league footballers</h1>
	</header>
    
    <nav role="navigation">
        <div id="menuToggle">
          <input type="checkbox" />
          <span></span>
          <span></span>
          <span></span>
   
          <ul id="menu">
            <a href="{% url 'foot_tweet_app:index' %}"><li>Home</li></a>
            <a href="{% url 'foot_tweet_app:help' %}"><li>Help</li></a>
          </ul>
        </div>
      </nav>
    {% block content %}
    <div id='container'>   
            <div id='button1'>
                    <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Arsenal">
                        <img src="{% static "images/arsenal.png" %}" alt="Arsenal" />
                    </a><br>
                    <h3 style="text-align: center; margin-block-start: 0px;">Arsenal</h3>
            </div>
                  
           <div id='button1'>
                <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Aston Villa">
                    <img src="{% static "images/AstonVilla.png" %}" alt="AstonVilla" />
                </a>
                <h3 style="text-align: center; margin-block-start: 0px;">Aston Villa</h3>
            </div>
           <div id='button1'>
                <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Brighton and Hove Albion">
                    <img src="{% static "images/brighton_and_hove_albion.png" %}" alt="brighton_and_hove_albion" />
                </a>
                <h3 style="text-align: center; margin-block-start: 0px;">Brighton and Hove Albion</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Burnley">
               <img src="{% static "images/burnley.png" %}" alt="burnley" />
            </a>
            <h3 style="text-align: center; margin-block-start: 0px;">Burnley</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Chelsea">
               <img src="{% static "images/chelsea.png" %}" alt="chelsea" />
            </a>
            <h3 style="text-align: center; margin-block-start: 0px;">Chelsea</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Crystal Palace">
               <img src="{% static "images/crystal_palace.png" %}" alt="crystal_palace" />
            </a>
            <h3 style="text-align: center; margin-block-start: 0px;">Crystal Palace</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Everton">
               <img src="{% static "images/everton.png" %}" alt="everton" />
            </a>
            <h3 style="text-align: center; margin-block-start: 0px;">Everton</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Fulham">
               <img src="{% static "images/fulham.png" %}" alt="fulham" />
            </a>
            <h3 style="text-align: center; margin-block-start: 0px;">Fulham</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Leeds United">
                <img src="{% static "images/leeds_united.png" %}" alt="leeds_united" />
            </a> 
            <h3 style="text-align: center; margin-block-start: 0px;">Leeds United</h3>  
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Leicester City">  
                <img src="{% static "images/leicester_city.png" %}" alt="leicester_city" />
            </a> 
            <h3 style="text-align: center; margin-block-start: 0px;">Leicester City</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Liverpool"> 
                <img src="{% static "images/liverpool.png" %}" alt="liverpool" />
            </a> 
            <h3 style="text-align: center; margin-block-start: 0px;">Liverpool</h3> 
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Manchester City">   
                <img src="{% static "images/manchester_city.png" %}" alt="manchester_city" />
            </a>
            <h3 style="text-align: center; margin-block-start: 0px;">Manchester City</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Manchester United">   
                <img src="{% static "images/manchester_united.png" %}" alt="manchester_united" />
            </a>
            <h3 style="text-align: center; margin-block-start: 0px;">Manchester United</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Newcastle United">   
                <img src="{% static "images/newcastle_united.png" %}" alt="newcastle_united" />
            </a>
            <h3 style="text-align: center; margin-block-start: 0px;">Newcastle United</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Sheffield United">
                <img src="{% static "images/sheffield_united.png" %}" alt="sheffield_united" />
            </a> 
            <h3 style="text-align: center; margin-block-start: 0px;">Sheffield United</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Southampton">   
                <img src="{% static "images/southampton.png" %}" alt="southampton" />
            </a>
            <h3 style="text-align: center; margin-block-start: 0px;">Southampton</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Tottenham Hotspur">  
                <img src="{% static "images/tottenham_hotspur.png" %}" alt="tottenham_hotspur" />
            </a> 
            <h3 style="text-align: center; margin-block-start: 0px;">Tottenham Hotspur</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=West Bromwich Albion">   
                <img src="{% static "images/West_Bromwich_Albion.png" %}" alt="West_Bromwich_Albion" />
            </a>
            <h3 style="text-align: center; margin-block-start: 0px;">West Bromwich Albion</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=West Ham United">  
                <img src="{% static "images/West_Ham_United.png" %}" alt="West_Ham_United" />
            </a> 
            <h3 style="text-align: center; margin-block-start: 0px;">West Ham United</h3>
            </div>
           <div id='button1'>
            <a href="{% url 'foot_tweet_app:show_team' %}?team_name=Wolverhampton Wanderers">
                <img src="{% static "images/Wolverhampton_Wanderers.png" %}" alt="Wolverhampton_Wanderers" />
            </a>  
            <h3 style="text-align: center; margin-block-start: 0px;">Wolverhampton Wanderers</h3>
            </div>
     </div>
     {% endblock %}
</body>
</html>

foot_tweet_app/templates/player.html
<!DOCTYPE html>
{% extends "index.html" %}
{% load static %}

{% block body_block%}
{% block content %}
<body>
    <script type="text/javascript">
        document.getElementById("headr").innerHTML="{{ player_name }}";
        </script>

    <a style="float: right;padding-right: 5%; font-size:30px" href = "javascript:history.back()"><i class="fa fa-arrow-circle-left"></i></a>

    <div id="container" style="width: 700px; height: 400px; padding-left:20% ;"></div>
        <script src="https://code.highcharts.com/highcharts.src.js"></script>
        <script type="text/javascript">
            Highcharts.chart('container', {{ chart|safe }});
        </script>
        
        <br>

    <div style="padding: 10px; border: groove; margin: auto; width: 650px;">
        <h3 style="text-align: center;">{{ insight }}</h3>
        </div>

</body>
{% endblock %}
{% endblock %}
</html>

foot_tweet_app/templates/teams.html
<!DOCTYPE html>
{% extends "index.html" %}
{% load static %}

{% block body_block%}
{% block content %}
<body>
  <script type="text/javascript">
    document.getElementById("headr").innerHTML="{{ team_name }}";
    </script>    
  <a style="float: right;padding-right: 5%; font-size:30px" href = "javascript:history.back()"><i class="fa fa-arrow-circle-left"></i></a>
  <br>
   <div class="float-container">
    <div class="float-child-left">
      <table>
      <!-- <table style="width:50%; float: left;"> -->
        <tr>
          <th>Recent Tweets - <i>{{ team_name }}</i></th>
        </tr>
        {% for tweet in team_tweets %}
        <tr>
            <td style="text-align: left;">{{ tweet }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
    
    <div class="float-child-right">
      <!-- <table style="width:50%; float: left;"> -->
        <table>
        <tr>
          <th>Position of Player</th>
          <th>Player Name</th>
        </tr>
        {% for t in team %}
        <tr>
            <td>{{ t.player_position }}</td>
            <td><a href="{% url 'foot_tweet_app:show_player' %}?player_name={{ t.player_name }}">{{ t.player_name }}</a></td>
        </tr>
        {% endfor %}
      </table>
    </div>
    </div>
 
<style>
    table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}

th, td {
    text-align: center;
  padding: 10px;
}

th {
  background-color: blueviolet;
}

table {
  border-spacing: 5px;
}
</style>
</body>
{% endblock %}
{% endblock %}
</html>